# This file was generated by the {rix} R package v0.18.2 on 2026-04-12
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = c("reactable",
#  > "reactablefmtr@2.0.0",
#  > "htmltools",
#  > "dplyr",
#  > "tidyr",
#  > "anytime",
#  > "pointblank",
#  > "lubridate"),
#  > system_pkgs = c("air-formatter",
#  > "quarto"),
#  > ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-27.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      anytime
      dplyr
      htmltools
      lubridate
      pointblank
      reactable
      tidyr;
  };
  
    reactablefmtr = (pkgs.rPackages.buildRPackage {
      name = "reactablefmtr";
      src = pkgs.fetchzip {
       url = "https://cran.r-project.org/src/contrib/Archive/reactablefmtr/reactablefmtr_2.0.0.tar.gz";
       sha256 = "sha256-QWdHdARAhm0mOYMeAvPFjhe62t1AkpsMFfxvjbGh1JA=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          reactable
          dplyr
          htmltools
          htmlwidgets
          magrittr
          purrr
          sass
          shiny
          stringr
          tippy
          webshot;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      air-formatter
      glibcLocales
      nix
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ reactablefmtr rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
