---
title: "PodcastIndex Dashboard"
format: 
  dashboard:
    logo: assets/img/brand-icon.svg
    nav-buttons:
      - github
      - icon: mastodon
        href: https://podcastindex.social/@rpodcast
      - icon: twitter
        href: https://twitter.com/theRcast  
      - icon: broadcast-pin
        href: https://podcastindex.org
    theme: [cosmo, custom.scss]
execute: 
  echo: false
params:
  dev_mode: false
  pointblank_object_path: "https://podcast20-projects.us-east-1.linodeobjects.com/exports/podcastdb_pointblank_object/podcastdb_pointblank_object"
  podcast_dup_df_path: "https://podcast20-projects.us-east-1.linodeobjects.com/exports/podcast_dup_df.rds"
  podcast_analysis_df_path: "https://podcast20-projects.us-east-1.linodeobjects.com/exports/analysis_metrics_df.rds"
  podcast_log_path: "https://podcast20-projects.us-east-1.linodeobjects.com/logs/"
---


```{r}
#| context: setup
#| label: setup-chunk

# load packages
library(reactable)
library(reactablefmtr)
library(htmltools)
library(dplyr)
library(pointblank)
library(anytime)

# load supporting functions
source("R/utils.R")
source("R/fct_tables.R")

# obtain record objects from object storage
pointblank_object <- podcastdb_pointblank_object(url = params$pointblank_object_path, dev_mode = params$dev_mode)
podcast_dup_df <- podcastdb_dupdf_object(url = params$podcast_dup_df_path, dev_mode = params$dev_mode)
analysis_metrics_df <- podcastdb_analysisdf_object(url = params$podcast_analysis_df_path, dev_mode = params$dev_mode)
podcast_db_date  <- podcastdb_log_object(root_url = params$podcast_log_path, date = as.character(lubridate::today())) |> date_report()
```

# Duplicates

## Record Summary Row

```{r}
#| label: n-groups
#| content: valuebox
#| title: "Duplicate Groups"

records <- length(unique(analysis_metrics_df$record_group))
list(
  icon = 'stack',
  color = 'primary',
  value = number(records)
)
```

```{r}
#| label: med-n-records
#| content: valuebox
#| title: "Median records per group"

med_records <- median(analysis_metrics_df$n_records)
list(
  icon = 'mic',
  color = 'primary',
  value = number(med_records)
)
```

## Record Analysis Row

::: {.card title="Duplicates Data Viewer"}
```{r}
#| label: duplicates-viewer
# re-order columns
analysis_metrics_df <- analysis_metrics_df |>
  select(record_group, n_records, everything())

if (params$dev_mode) {
  analysis_metrics_df <- dplyr::slice(analysis_metrics_df, 1:30)
}

record_analysis_table(analysis_metrics_df, podcast_dup_df, report_date = podcast_db_date)
```
:::

# Data Quality

## Pointblank validation set row

```{r}
#| label: process-pointblank-extracts
pb_extracts <- get_data_extracts(pointblank_object)
pb_extracts <- purrr::map_at(
  pb_extracts,
  c('1', '3', '4', '7'),
  ~clean_podcast_df(.x, dev_mode = params$dev_mode)
)
```

::: {.card title="Validation Summary"}

```{r}
#| label: pointblank-viewer
pointblank_table(pointblank_object, report_date = podcast_db_date, extracts = pb_extracts)
```
:::

# Methodology

{{< include methods.md >}}