on:
  push:
    branches: [main]
    paths:
    - 'index.qmd'
    - 'R/*.R'
  schedule:
  - cron: "5 9 * * 0"
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
  
      - name: Build development environment
        run: |
          nix-build

      - name: Render and Publish
        uses: b-rodrigues/quarto-nix-actions/publish@main
        with:
          target: gh-pages
          path: index.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
